### PR TITLE
Added casts to squelch warnings emitted by VC2010.

### PR DESCRIPTION
**Pull request by wintersteiger**
Should be syntatic only.

### CODE REVIEW

**Comment by msprotz** [comment]
This looks good to me but these things are tricky and I'd like to get a second pair of eyes to confirm we're not tripping on some corner case. @tahina-pro can you confirm that per the C standard, this doesn't change the semantics of the code?

I particular: for n of type uint32_t, are `-n` and `-(int32_t)n` the same thing? (i.e. in the first case is the integer promotion rule stating that `n` gets converted to signed without an extension?)

It shouldn't matter since n is less than 32 in any case, but still...

**Comment by wintersteiger** [comment]
Good point! Technically, this may be undefined behavior in some versions of the C standard. We can turn `-n` into `(~n + 1)` to make it obvious what should happen.

**Comment by wintersteiger** [comment]
@tahina-pro just checking, did you have a chance to look at this?

**Comment by msprotz** [comment]
Closing this because I've removed the rotate functions. Seeing how easy these are to get wrong, didn't want to keep these in my tree :)

**Pull request closed without merging**
