### PR TITLE
Update types.h

### PR DESCRIPTION
**Pull request by franziskuskiefer**
The `elif` branch here also needs make sure we're on a x64 machine.

### CODE REVIEW

**Comment by msprotz** [comment]
Thanks Franziskus, this seems sensible. Re-running CI to see if we get a green (I don't see why not).

**Comment by msprotz** [comment]
Famous last words, the linux build failed. Looking into it...

**Comment by msprotz** [comment]
```
[STDOUT]/home/everest/kremlin/kremlib/dist/generic/libkremlib.a(fstar_bytes.o): In function `FStar_Bytes_uint128_of_bytes':
[STDOUT]/home/everest/kremlin/kremlib/dist/generic/fstar_bytes.c:193: undefined reference to `FStar_UInt128_uint64_to_uint128'
[STDOUT]/home/everest/kremlin/kremlib/dist/generic/fstar_bytes.c:195: undefined reference to `FStar_UInt128_shift_left'
[STDOUT]/home/everest/kremlin/kremlib/dist/generic/fstar_bytes.c:196: undefined reference to `FStar_UInt128_uint64_to_uint128'
[STDOUT]/home/everest/kremlin/kremlib/dist/generic/fstar_bytes.c:196: undefined reference to `FStar_UInt128_logxor'
```

**Comment by msprotz** [comment]
According to https://sourceforge.net/p/predef/wiki/Architectures/ _M_X64 is only defined by Visual Studio, meaning this check will always be false since it follows `!defined(_MSC_VER)`.

Did you intend for something like `__x86_64__`?

**Comment by franziskuskiefer** [comment]
> Did you intend for something like `__x86_64__`?

yeah.... we should do `__x86_64__` or `__x86_64`. Unfortunately `build_local.sh` doesn't work for me so lets see what the CI says.

**Comment by msprotz** [comment]
CI failed but that's because your branch is now slightly behind master...

**Pull request closed without merging**
