### PR TITLE
Grow the WASM memory if the data being passed in is too large to fit …

### LINKED ISSUE #217: The js backend should better handle OOM
The `reserve` function in `loader.js` doesn't check that there is enough memory before returning.
This can result in the following error when accessing the "reserved" memory. 

```
RangeError: offset is out of bounds
```

This was spotted using `hacl-star` with large input.

- consider dynamically growing the memory buffer (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/grow)
- make `reserve` raise a proper OOM error.

### PR DESCRIPTION
**Pull request by msprotz**
…in the memory. This fixes #217

### CODE REVIEW

**Comment by msprotz** [comment]
@hhugo can you please give this a try and let me know if this fixes your problem?

**Comment by hhugo** [comment]
I don't have time to check this now but it looks very similar to what I hack myself while debugging.

Thinking more about this. It looks like we never reclaim any memory. Is there any reason no to use malloc + free ?

**Comment by msprotz** [comment]
The JS bindings for HACL restore the stack pointer to reclaim the memory here: https://github.com/project-everest/hacl-star/blob/master/bindings/js/api.js#L284

Regarding malloc & free: the kremlin-to-WASM direct compilation pipeline does not depend on any libc and does not implement malloc/free, only stack allocations with a simple bump-pointer allocator. The top-of-the-stack mark is a uint32 at index 0 of the memory, and initially starts with 128 to leave a little space for a simple debug protocol I have been using in the past (see loader.js:400).

**Comment by msprotz** [comment]
The HACL code does not use malloc or free, and therefore, can be safely compiled by the kremlin-to-WASM direct pipeline.

**Comment by msprotz** [comment]
@hhugo can you tell me whether this fixes your issue before I merge? thanks!

**Comment by hhugo** [comment]
It does fix my issue. Thanks

**Pull request merged**
