### PR TITLE
Don't overwrite OCAMLPATH in Makefile

### PR DESCRIPTION
**Pull request by pierrebeaucamp**
This is exactly the same issue as https://github.com/FStarLang/FStar/pull/1456

Essentially, instead of overwriting the entire `OCAMLPATH` to include the fstar library, we just append it instead.

### CODE REVIEW

**Comment by msprotz** [comment]
Looks good, thanks!

**Comment by msprotz** [comment]
I had to revert this because it broke our windows tests: even on cygwin, OCAMLPATH is semicolon-separated. I'll push a fix later.

**Comment by pierrebeaucamp** [comment]
Ah sorry, I did not know this. I assumed OCAMLPATH followed similar behavior as the Unix PATH. Sorry for breaking things

**Comment by msprotz** [comment]
No worries, I didn't notice either until CI ran

**Pull request merged**
