### PR TITLE
Migrate OMP to ppxlib-0.22.0

### PR DESCRIPTION
**Pull request by fangyi-zhou**
https://github.com/FStarLang/FStar/pull/2247#issuecomment-797409569

Now that the `visitors` package hasn't supported ppxlib-0.22.0 yet, we need to wait for that the happen before merging this commit. In my local setup, I installed manually the patched version for this commit.

### CODE REVIEW

**Review by msprotz — APPROVED** [review]
Based on a cursory glance this looks great. Can you let me know once this is ready for merging?

@victor-dumitrescu you might want to take a look at this since you're the initial author of the GenCTypes module... thanks!

**Comment by victor-dumitrescu** [comment]
Thanks, I think it looks good! We'll have to see what the diff is in the produced code wrt to the HACL snapshot in dist/gcc-compatible but I don't expect it to be functionally different.

**Comment by beurdouche** [comment]
François just released the new version of `visitors` requiring `ppxlib.0.22.0`, so it should be in opam soon.
https://github.com/ocaml/opam-repository/pull/18352

**Comment by msprotz** [comment]
Thanks @fangyi-zhou! Much appreciated.

@beurdouche did the OCaml version bump happen on the F* side? if so, I can easily merge the wasm1.1 branch and now everything should work out of the box on a fresh setup

**Pull request merged**
